### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function switch_to_blog()

### ISSUE THREAD

**Issue by erichuang2015** [martinosmartinos/Mongabay-Wordpress-Theme#83]
Hello

I am using this theme.

WordPress 4.9.8
XAMPP V3.2.2  with bitnami wordpress module
PHP Version 7.2.10
Apache/2.4.34 

I installed this theme successfully, when I go to the homepage, it show ERRORS 

Fatal error: Uncaught Error: Call to undefined function switch_to_blog() in C:\xampp\apps\wordpress\htdocs\wp-content\themes\Mongabay\functions.php:84 Stack trace: #0 C:\xampp\apps\wordpress\htdocs\wp-includes\class-wp-hook.php(286): mongabay_mega_query(Object(WP_Query)) #1 C:\xampp\apps\wordpress\htdocs\wp-includes\class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #2 C:\xampp\apps\wordpress\htdocs\wp-includes\plugin.php(515): WP_Hook->do_action(Array) #3 C:\xampp\apps\wordpress\htdocs\wp-includes\class-wp-query.php(1634): do_action_ref_array('pre_get_posts', Array) #4 C:\xampp\apps\wordpress\htdocs\wp-includes\class-wp-query.php(3230): WP_Query->get_posts() #5 C:\xampp\apps\wordpress\htdocs\wp-includes\class-wp.php(599): WP_Query->query(Array) #6 C:\xampp\apps\wordpress\htdocs\wp-includes\class-wp.php(715): WP->query_posts() #7 C:\xampp\apps\wordpress\htdocs\wp-includes\functions.php(960): WP->main('') #8 C:\xampp\apps\wordpress\htdocs\wp-blog-header.php(16): wp() #9 C:\xampp\apps\wordpress\htdocs\index.php(17) in C:\xampp\apps\wordpress\htdocs\wp-content\themes\Mongabay\functions.php on line 84

**Comment by erichuang2015** [comment]
sorry I have to correct my xampp version is the latest 7.2.10

**Comment by martinosmartinos** [comment]
@erichuang2015 there few things to take in consideration before you start using this wordpress template:
- template is custom tailored for specific website which is why it will fail if setup of yours is different.
- template is for multisite installation

Error you get is referring to your single site installation. It has to be multisite where switch_to_blog() function is used. There is a single site version of this template in my repository though: https://github.com/martinosmartinos/Mongabay-Indonesia-Wordpress-Theme

But again, you will run into other issues where code/functions are custom tailored;) Good luck!
